#!/usr/local/bin/perl -T 


use strict;
use warnings;

use lib qw(/var/www/lib/core);
use lib qw(/var/www/lib/S_pombe);
use SangerWeb;


use pombetv::pombetv_module;


#########
# Author:        fs3
# Group:         team 79
#
# Entrance page for transcriptome viewer (pombetv)
#


our $VERSION = do { my @r = (q$Revision: 0.1 $ =~ /\d+/mxg); sprintf '%d.'.'%03d' x $#r, @r };

main();
1;

sub main {

  my $sw  = SangerWeb->new({
    'title'   => q(Pombe TV),
    'banner'  => q(TranscriptomeViewer),
#    'inifile' => SangerWeb->document_root() . "/header.ini",
  });

  my $cgi                 = $sw->cgi();
  my $condition           = $cgi->param('condition')  || 13;
  my $genename            = $cgi->param('genename')  || q();
  my $action              = $cgi->param('action') || q();
  my $id_from_cgi         = $cgi->param('ID') || q();

  my $affy_column_name=find_affy_column_name_to_condition($condition);
  my $solexa_column_name=find_solexa_column_name_to_condition($condition);
  

#  print $sw->header();
 print qq(Content-type: text/html\n\n);

print qq (<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Bahler Lab</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/css/other.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="header">
<div style="text-align:left; margin-left:70px; margin-bottom:0px; margin-top:0px;"><span style="text-shadow:#FFF; font-family:'Arial Black', Gadget, sans-serif; font-size:32pt; color:#EBF1DE; ">b&auml;hler</span><span style="text-shadow:auto; font-family:'Arial Black', Gadget, sans-serif; font-size:32pt; color:#77933C; ">lab&#13;</span></div>
  <div style="text-align:left; margin-left:30px; margin-top:0px;"><span style="font-family:'Arial Black', Gadget, sans-serif; font-size:20pt; color:#4F6228; "> Genome Regulation</span></div>
  <div class="O">
  <div style="text-align:center; margin-bottom:0; margin-top:-59px; margin-left:120px;margin-right:-20px;"><span style="font-family:Arial, Helvetica, sans-serif; font-size:80pt; color:#D7E4BD; "><strong><em>pombeTV&#13;</em></strong></span></div>
<div style="text-align:right; margin-bottom:0; margin-top:-78px; margin-left:150px;margin-right:20px;"><span style="font-family:'Arial Black', Helvetica, sans-serif; font-size:36pt; color:white; ">UCL</span></div>
  <div></div>
</div>


</div>
<div id="sidebar">
                <div id="menu">
                        <ul>
                                <li ><a href="/index.html" title="">Home</a></li>
                                <li><a href="/group" title="">People</a></li>
                                <li><a href="/research.htm" title="">Research</a></li>
                                <li><a href="/publications" title="">Publications</a></li>
                                <li class="active first"><a href="/software" title="">Resources</a></li>

                                <li ><a href="/cont.htm" title="">Contact</a></li>
                        </ul>
                </div>


        </div><div id="content">

                <div class="feature bg7">
        </div>

                        <div class="content" >

);

  #########
  # print page content
  #
  
  my @return_values=();
  my $status=0;
  my @IDs = ();
  my @descriptions = ();
  my @genenames = ();

  if ($action eq "Submit" && $id_from_cgi ne "") {
    # Use the ID from the CGI script (user choice of a gene from a list)
    ($IDs[0],$genenames[0],$descriptions[0])=split(/;/,$id_from_cgi);
    $status=1;
    $genename=$genenames[0];
  } else {
    # Use the input from the CGI-script
    @return_values=search_gene_name($genename);
    $status= shift @return_values;
    @IDs   = @{shift @return_values};
    @genenames = @{shift @return_values};
    @descriptions = @{shift @return_values};
  }

  my $condition_name = find_condition_name($condition);

  if ($status==2) {  # More than one gene found, show gene selection dialogue
    my @ID_genenames_descriptions=();
    foreach my $index(0..$#IDs) {
      push@ID_genenames_descriptions, "$IDs[$index];$genenames[$index];$descriptions[$index]";
    }

    show_gene_selection_form(\@ID_genenames_descriptions,\@descriptions,$condition);
  }
  elsif ($status==1) { # One gene found, include links to images with the gene IDs 

    print '<table width="100%">
           <tr> 
           <td align="left" valign="top">';
    show_main_form($condition,$genename);

    print ' </td> 
            <td align="right" valgin="top"> ';
    show_citation(1);
    print '</td></tr></table>';

    print '<div align="center">';
    print ("<BR><BR><H4>Tiling array profile</H4>");
    if ($affy_column_name eq "") {
      print "<BR> Tiling array profiles were not measured for this condition. <BR><BR>";
    } else {
      print "<BR>for gene <B>$descriptions[0]</B> and condition <B>$condition_name</B> </p><BR>";
      if (try_fetch_image($IDs[0],$affy_column_name)){
	print '<img src="/cgi-bin/pombetv/show_image?';
	print   'id=',$IDs[0],'&c=',$affy_column_name,'">';
      } else {
	print "is not available";
      }
    }
      print ("<BR><BR><H4>Illumina sequencing profile</H4>");

    if ($solexa_column_name eq "") {
      
      print "<BR> Illumina sequencing profiles were acquired for the following conditions only: YE, M1, M2, M3, M4, M5. </UL>.";
    } 
    else {       
       print (" <BR>for gene <B>$descriptions[0]</B> and condition <B>$condition_name</B> </p><BR>");
       if (try_fetch_image($IDs[0],$solexa_column_name)){
	 print '<img src="/cgi-bin/pombetv/show_image?';
	 print   'id=',$IDs[0],'&c=',$solexa_column_name,'">';
      } else {
	print "is not available";
      }
    }
    print '</div align="center">';    
  }
  elsif ($status==3) { # No gene found
    print ('<BR><BR><p> The gene name "<B>',$genename,'"</B> could not be identified.<BR>');
    print ('Please try another one. All gene names from geneDB are valid. <BR>');
    show_main_form($condition,"");
  show_citation;
   show_citation_links;
  }
  else {
    print ("Internal error");
  }
print ' </div>
        </div>
';
#  print $sw->footer();
  return();
}

